[env:ESP32_2432S028R]
platform = espressif32 @ 6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200

# Expande o tamanho máximo do aplicativo para 3MB (Desativa OTA)
board_build.partitions = huge_app.csv
board_build.flash_mode = qio

build_flags = 
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D TFT_INVERSION_ON=1
    -D DETECT_SCREEN=1
    -w
    -zmuldefs

lib_deps =
    bblanchon/ArduinoJson @ 6.21.3
    adafruit/Adafruit GFX Library @ ^1.11.9
    https://github.com/bmorcelli/ESPAsyncWebServer.git
    esphome/AsyncTCP-esphome @ ^2.1.3
    bodmer/TFT_eSPI @ ^2.5.43